[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Ignore specific compiler warnings
ignored_error_codes = [1878, 5574]

# File system permissions
fs_permissions = [{ access = "read", path = "./"}]

# Remappings for imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Gas reporting
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
